//prueba de login y register

###login
POST http://localhost:1234/auth/login
Content-Type:application/json

{
  "email":"1",
  "password":"1"
}

###logout de usuario
POST http://localhost:1234/auth/logout

###perfil del usuario
GET http://localhost:1234/auth/profile

### update de usuario
PATCH http://localhost:1234/auth/update
Content-Type:application/json

{
    "name":"3",
    "email":"3",
    "password":"3",
    "address":{
        "street":"marte",
        "city":"swat",
        "state":"NOSE",
        "zip":"452",
        "country":"NOSE"
      },
    "phone":"777-777-777"
}

###register
POST http://localhost:1234/auth/register
Content-Type:application/json

{
    "name":"344",
    "email":"344",
    "password":"344",
    "address":{
        "street":"NOSE",
        "city":"NOSE",
        "state":"NOSE",
        "zip":"452",
        "country":"NOSE"
      },
    "phone":"123-3421-123"
}


//items

###obtener todos los items
GET  http://localhost:1234/items/items

###obtener un item
GET http://localhost:1234/items/item/6684e57d7d08d26847b4c927

###crear un item
POST http://localhost:1234/items/createItems
Content-Type:application/json

{
  "name": "aasw ",
  "price": 2.00,
  "description": "awasa",
  "category": "vwasa",
  "stock": 1,
  "images":["imagen"]
}

###borrar un item
DELETE  http://localhost:1234/items/deleteItems/6687b22de578e1c67cae7323

###update un item
PATCH http://localhost:1234/items/updateItems/6687b22de578e1c67cae7323
Content-Type:application/json

{
    "name": "gato naranja",
    "stock": 140
}



