//prueba de login y register

###login
POST http://localhost:1234/auth/login
Content-Type:application/json

{
  "email":"a",
  "password":"a"
}

###logout de usuario
POST http://localhost:1234/auth/logout

###perfil del usuario
GET http://localhost:1234/auth/profile

### update de usuario
PATCH http://localhost:1234/auth/update
Content-Type:application/json

{
    "name":"juan perez",
    "email":"a",
    "address":{
        "street":"a",
        "city":"a",
        "state":"a",
        "zip":"a",
        "country":"a"
      },
    "phone":"777-777-777"
}

###register
POST http://localhost:1234/auth/register
Content-Type:application/json

{
    "name":"jaime ramos",
    "email":"jramosabr05@gmail.com",
    "password":"123",
    "address":{
        "street":"a",
        "city":"a",
        "state":"a",
        "zip":"a",
        "country":"a"
      },
    "phone":"6730-20381"
}


//items

###obtener todos los items
GET  http://localhost:1234/items/items

###obtener un item
GET http://localhost:1234/items/item/668b96617e0749f1713fb99d

###crear un item
POST http://localhost:1234/items/createItems
Content-Type:application/json

{
  "name": "a2",
  "price": 105.00,
  "description": "papel",
  "category": "utiles",
  "stock": 5,
  "images":["imagen"]
}

###borrar un item
DELETE  http://localhost:1234/items/deleteItems/668b96617e0749f1713fb99d

###update un item
PATCH http://localhost:1234/items/updateItems/6687b22de578e1c67cae7323
Content-Type:application/json

{
    "name": "gato naranja",
    "stock": 140
}

//cart pruebas

### add cart
POST http://localhost:1234/a/cart/addCart/668935a43fbadff4bb064410

### odtener el cart
GET http://localhost:1234/a/cart/getCart


//payment pruebas

###createpay
POST http://localhost:1234/a/pay/createOrder

###capturepay
//hay que colocar el token
GET  http://localhost:1234/a/pay/captureOrder

###cancelpay
GET http://localhost:1234/a/pay/canecelOrder

